# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Rename the entrypoint file to use ES modules if needed
RUN [ -f rss-to-md-server.js ] && mv rss-to-md-server.js rss-to-md-server.mjs || echo 'File already renamed'

# Start the MCP server using the renamed entrypoint
CMD [ "node", "rss-to-md-server.mjs" ]
